server:
  port: 7070

spring:
  application:
    name: "resource-server"

  datasource:
    username: myuser
    password: secret
    url: "jdbc:postgresql://127.0.0.1:5432/shop_db"

  sql:
    init:
      mode: always

  docker:
    compose:
      skip:
        in-tests: false
      file: "./../../compose.yaml"