server:
  port: 7070

spring:
  application:
    name: "resource-server"

  config:
    import: "optional:classpaht:./../../../../../secrets.properties"

  datasource:
    username: myuser
    password: secret
    url: "jdbc:postgresql://127.0.0.1:5432/shop_db"

  sql:
    init:
      mode: always

  session:
    redis:
      repository-type: indexed
      namespace: "spring:session:resource"

#  data:
#    redis:
#      host: ${REDIS_HOST:localhost}
#      port: ${REDIS_PORT:6379}
  #      password:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:9090}

logging:
  level:
    org.springframework:
      security: trace