server:
  port: 9090

spring:
  application:
    name: "authorization-server"

  config:
    import: "optional:classpaht:./../../../../../secrets.properties"

  security:
    oauth2:
      authorizationserver:
        client:
          client-1:
            registration:
              client-id: "client"
              client-secret: ${AUTH_CLIENT_SECRET}
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - ${REDIRECT_URIS:http://127.0.0.1:8080/login/oauth2/code/spring}
              post-logout-redirect-uris:
                - ${REDIRECT_URIS:http://127.0.0.1:8080/shop}
              scopes:
                - "openid"
            require-authorization-consent: true
            require-proof-key: true

      client:
        registration:
          google:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  level:
    org.springframework.security: trace
